import { demoMission } from "../../../scripts/lib/wgos-config.mjs";

export const missionTemplates = {
  DEMO_SYSTEM_VALIDATION: {
    id: "DEMO_SYSTEM_VALIDATION",
    title: "WGOS Demo System Validation",
    companyId: demoMission.companyId,
    objective: demoMission.objective,
    approvalClass: "A1",
    successCriteria: demoMission.successCriteria,
    workflows: ["WORKFLOW_ORCHESTRATION", "DOCUMENTATION_UPDATE_WORKFLOW", "QA_AND_RELEASE_WORKFLOW"],
    specialistBlueprints: [],
  },
  BUILD_PREMIUM_WEBSITE: {
    id: "BUILD_PREMIUM_WEBSITE",
    title: "Build Premium Website",
    companyId: "web-growth",
    objective: "Plan and coordinate a premium website build with strategy, design, engineering, search, QA, memory, and documentation.",
    approvalClass: "A1",
    workflows: ["WEBSITE_REBUILD_WORKFLOW", "QA_AND_RELEASE_WORKFLOW"],
    successCriteria: ["Required departments selected", "Task dependencies clear", "Executive dashboard reflects progress"],
    specialistBlueprints: [
      { agentSlug: "PRODUCT_STRATEGIST_AGENT", objective: "Define business, audience, and page strategy.", expectedOutput: "Product strategy brief" },
      { agentSlug: "UI_UX_DESIGN_AGENT", objective: "Design the information and conversion structure.", expectedOutput: "UX structure plan" },
      { agentSlug: "FRONTEND_ENGINEER_AGENT", objective: "Plan implementation sequence and component structure.", expectedOutput: "Implementation plan" },
      { agentSlug: "SEO_AGENT", objective: "Define search, metadata, and internal linking requirements.", expectedOutput: "SEO requirements" },
    ],
  },
  REDESIGN_WEBSITE: {
    id: "REDESIGN_WEBSITE",
    title: "Redesign Website",
    companyId: "web-growth",
    objective: "Coordinate redesign strategy, UX, motion, engineering, SEO, and QA around a website refresh mission.",
    approvalClass: "A1",
    workflows: ["WEBSITE_REBUILD_WORKFLOW"],
    successCriteria: ["Redesign work is routed by department", "Dependencies and QA are explicit"],
    specialistBlueprints: [
      { agentSlug: "PRODUCT_STRATEGIST_AGENT", objective: "Review current site problems and redesign goals.", expectedOutput: "Redesign strategy brief" },
      { agentSlug: "UI_UX_DESIGN_AGENT", objective: "Define redesigned user flows and page structure.", expectedOutput: "UX redesign plan" },
      { agentSlug: "MOTION_GRAPHICS_AGENT", objective: "Define motion changes that support comprehension.", expectedOutput: "Motion redesign guidance" },
      { agentSlug: "FRONTEND_ENGINEER_AGENT", objective: "Map implementation requirements for the redesign.", expectedOutput: "Engineering redesign plan" },
      { agentSlug: "SEO_AGENT", objective: "Protect search intent and metadata during redesign.", expectedOutput: "Search protection plan" },
    ],
  },
  CLIENT_WEBSITE_DELIVERY: {
    id: "CLIENT_WEBSITE_DELIVERY",
    title: "Client Website Delivery Pipeline",
    companyId: "client-template",
    objective:
      "Route a complete premium client website lifecycle from discovery through strategy, design, engineering, search, QA, client review, launch preparation, and documentation.",
    approvalClass: "A1",
    workflows: ["CLIENT_PROJECT_DELIVERY_WORKFLOW", "WEBSITE_REBUILD_WORKFLOW", "QA_AND_RELEASE_WORKFLOW"],
    successCriteria: [
      "Client discovery, strategy, design, engineering, and launch preparation are routed in sequence",
      "Approval gates remain explicit for client review, publishing, deployment, and DNS work",
      "Documentation, memory, and handoff artifacts exist for the full delivery chain",
    ],
    specialistBlueprints: [
      { agentSlug: "SALES_CONSULTANT_AGENT", objective: "Capture discovery inputs, success metrics, constraints, and commercial fit.", expectedOutput: "Client discovery summary" },
      { agentSlug: "PRODUCT_STRATEGIST_AGENT", objective: "Define site strategy, page strategy, conversion goals, and revenue direction.", expectedOutput: "Website strategy brief" },
      { agentSlug: "UI_UX_DESIGN_AGENT", objective: "Map information architecture, navigation, user journeys, and responsive wireframes.", expectedOutput: "Information architecture plan" },
      { agentSlug: "BRAND_DESIGN_AGENT", objective: "Define brand integration, color system, type direction, and component visual language.", expectedOutput: "Brand integration plan" },
      { agentSlug: "MOTION_GRAPHICS_AGENT", objective: "Define hero storytelling, motion system, reduced-motion fallbacks, and performance-safe animation intent.", expectedOutput: "Motion system specification" },
      { agentSlug: "FRONTEND_ENGINEER_AGENT", objective: "Plan component implementation, design token usage, and responsive frontend delivery.", expectedOutput: "Frontend implementation plan" },
      { agentSlug: "BACKEND_ENGINEER_AGENT", objective: "Define backend requirements, forms, data handling, and integration boundaries.", expectedOutput: "Backend delivery plan" },
      { agentSlug: "SEO_AGENT", objective: "Define metadata, page targeting, internal linking, and page-level SEO requirements.", expectedOutput: "SEO delivery requirements" },
      { agentSlug: "AEO_AGENT", objective: "Identify answer-engine opportunities across FAQs, content framing, and summary blocks.", expectedOutput: "AEO opportunity map" },
      { agentSlug: "GEO_AGENT", objective: "Define generative-engine discoverability guidance and citation-safe knowledge packaging.", expectedOutput: "GEO guidance" },
      { agentSlug: "CONTENT_STRATEGIST_AGENT", objective: "Define page copy structure, FAQs, proof blocks, and content dependencies.", expectedOutput: "Content production brief" },
      { agentSlug: "PERFORMANCE_ENGINEER_AGENT", objective: "Set performance budgets, motion constraints, and Core Web Vitals guardrails.", expectedOutput: "Performance budget" },
      { agentSlug: "ACCESSIBILITY_ENGINEER_AGENT", objective: "Set accessibility review criteria for semantics, motion, forms, and contrast.", expectedOutput: "Accessibility release criteria" },
      { agentSlug: "CLIENT_SUCCESS_AGENT", objective: "Prepare client review checkpoints, revision handling, and approval-state communication.", expectedOutput: "Client review plan" },
      { agentSlug: "DEPLOYMENT_ENGINEER_AGENT", objective: "Prepare launch checklist, rollback thinking, and approval-gated release notes.", expectedOutput: "Deployment preparation package" },
    ],
  },
  SEO_AUDIT: {
    id: "SEO_AUDIT",
    title: "SEO Audit",
    companyId: "web-growth",
    objective: "Run a coordinated search, technical SEO, schema, analytics, QA, and documentation mission.",
    approvalClass: "A1",
    workflows: ["SEO_GROWTH_WORKFLOW", "ANALYTICS_REVIEW_WORKFLOW"],
    successCriteria: ["Search, revenue, and documentation teams align on findings", "Prioritized next actions created"],
    specialistBlueprints: [
      { agentSlug: "SEO_AGENT", objective: "Review search intent and content opportunity.", expectedOutput: "SEO findings" },
      { agentSlug: "TECHNICAL_SEO_AGENT", objective: "Review crawlability, canonicals, and route safety.", expectedOutput: "Technical SEO findings" },
      { agentSlug: "SCHEMA_AGENT", objective: "Review schema coverage and correctness.", expectedOutput: "Schema findings" },
      { agentSlug: "ANALYTICS_AGENT", objective: "Add traffic and conversion context to the audit.", expectedOutput: "Analytics context" },
    ],
  },
  HOMEPAGE_REBUILD: {
    id: "HOMEPAGE_REBUILD",
    title: "Homepage Rebuild Mission",
    companyId: "web-growth",
    objective: "Coordinate a homepage rebuild through strategy, design, engineering, SEO, accessibility, performance, QA, documentation, and memory.",
    approvalClass: "A1",
    workflows: ["WEBSITE_REBUILD_WORKFLOW"],
    successCriteria: [
      "Required specialist sequence is created",
      "Every task produces structured runtime output",
      "Dashboard and operator surfaces reflect mission progress",
    ],
    specialistBlueprints: [
      { agentSlug: "PRODUCT_STRATEGIST_AGENT", objective: "Define audience, offer hierarchy, and outcome goals.", expectedOutput: "Product strategy brief" },
      { agentSlug: "UI_UX_DESIGN_AGENT", objective: "Create page structure and UX priorities.", expectedOutput: "UX structure plan" },
      { agentSlug: "MOTION_GRAPHICS_AGENT", objective: "Define motion guidance with performance and reduced-motion constraints.", expectedOutput: "Motion specification" },
      { agentSlug: "FRONTEND_ENGINEER_AGENT", objective: "Plan implementation and technical dependencies.", expectedOutput: "Implementation plan" },
      { agentSlug: "SEO_AGENT", objective: "Review search intent, metadata, and internal link needs.", expectedOutput: "SEO requirements" },
      { agentSlug: "ACCESSIBILITY_ENGINEER_AGENT", objective: "Define accessibility review criteria.", expectedOutput: "Accessibility checklist" },
      { agentSlug: "PERFORMANCE_ENGINEER_AGENT", objective: "Define performance guardrails and likely bottlenecks.", expectedOutput: "Performance guardrails" },
    ],
  },
  LAUNCH_BLOG_CLUSTER: {
    id: "LAUNCH_BLOG_CLUSTER",
    title: "Launch Blog Cluster",
    companyId: "web-growth",
    objective: "Coordinate search, publishing, schema, QA, memory, and documentation around a blog cluster launch.",
    approvalClass: "A1",
    workflows: ["CONTENT_PUBLISHING_WORKFLOW", "SEO_GROWTH_WORKFLOW"],
    successCriteria: ["Publishing and search work is coordinated", "Cluster launch artifacts are documented"],
    specialistBlueprints: [
      { agentSlug: "SEO_AGENT", objective: "Define cluster search targets and internal linking goals.", expectedOutput: "Cluster SEO brief" },
      { agentSlug: "CONTENT_STRATEGIST_AGENT", objective: "Create the cluster brief and content plan.", expectedOutput: "Cluster content plan" },
      { agentSlug: "COPYWRITER_AGENT", objective: "Draft the key cluster content package.", expectedOutput: "Draft cluster content" },
      { agentSlug: "INTERNAL_LINKING_AGENT", objective: "Map support links and cluster relationships.", expectedOutput: "Internal linking map" },
      { agentSlug: "SCHEMA_AGENT", objective: "Define content-aligned schema requirements.", expectedOutput: "Schema requirements" },
    ],
  },
  TECHNICAL_SEO_CLEANUP: {
    id: "TECHNICAL_SEO_CLEANUP",
    title: "Technical SEO Cleanup",
    companyId: "web-growth",
    objective: "Coordinate technical SEO, engineering, QA, and documentation on a cleanup mission.",
    approvalClass: "A1",
    workflows: ["SEO_GROWTH_WORKFLOW", "QA_AND_RELEASE_WORKFLOW"],
    successCriteria: ["Search and engineering dependencies are explicit", "QA and reporting closeout is complete"],
    specialistBlueprints: [
      { agentSlug: "TECHNICAL_SEO_AGENT", objective: "Identify the technical SEO defects and risk order.", expectedOutput: "Cleanup backlog" },
      { agentSlug: "FULL_STACK_ENGINEER_AGENT", objective: "Map implementation and dependency requirements.", expectedOutput: "Engineering cleanup plan" },
      { agentSlug: "PERFORMANCE_ENGINEER_AGENT", objective: "Identify performance-side search risks.", expectedOutput: "Performance risk note" },
    ],
  },
  WEEKLY_ANALYTICS_REVIEW: {
    id: "WEEKLY_ANALYTICS_REVIEW",
    title: "Weekly Analytics Review",
    companyId: "web-growth",
    objective: "Coordinate revenue, marketing, search, executive, and documentation around a weekly analytics mission.",
    approvalClass: "A1",
    workflows: ["ANALYTICS_REVIEW_WORKFLOW", "WEEKLY_AGENCY_OPERATIONS_WORKFLOW"],
    successCriteria: ["Traffic, pipeline, and revenue signals are summarized", "Executive recommendations are generated"],
    specialistBlueprints: [
      { agentSlug: "ANALYTICS_AGENT", objective: "Summarize traffic, conversions, and revenue signals.", expectedOutput: "Analytics summary" },
      { agentSlug: "CRO_AGENT", objective: "Convert analytics findings into conversion opportunities.", expectedOutput: "CRO recommendations" },
      { agentSlug: "MARKETING_STRATEGIST_AGENT", objective: "Translate metrics into channel and campaign priorities.", expectedOutput: "Marketing priorities" },
    ],
  },
  SEO_GROWTH_SPRINT: {
    id: "SEO_GROWTH_SPRINT",
    title: "SEO Growth Sprint",
    companyId: "web-growth",
    objective: "Coordinate continuous SEO growth across metadata, schema, internal linking, page speed, AEO, GEO, and reporting without making external state changes.",
    approvalClass: "A1",
    workflows: ["SEO_GROWTH_WORKFLOW", "ANALYTICS_REVIEW_WORKFLOW"],
    successCriteria: [
      "SEO opportunities are prioritized by impact and effort",
      "AEO and GEO improvements are documented alongside technical SEO work",
      "Growth reporting and next actions are captured for follow-through",
    ],
    specialistBlueprints: [
      { agentSlug: "SEO_AGENT", objective: "Prioritize metadata, CTR, and internal-linking opportunities.", expectedOutput: "SEO growth priorities" },
      { agentSlug: "TECHNICAL_SEO_AGENT", objective: "Review crawlability, canonicals, indexability, and page-speed blockers.", expectedOutput: "Technical SEO remediation plan" },
      { agentSlug: "SCHEMA_AGENT", objective: "Expand structured-data opportunities tied to visible content.", expectedOutput: "Schema expansion plan" },
      { agentSlug: "AEO_AGENT", objective: "Identify answer-engine opportunities across FAQs, summaries, and snippet targeting.", expectedOutput: "AEO opportunities" },
      { agentSlug: "GEO_AGENT", objective: "Identify generative-engine discoverability improvements and citation-safe content structure.", expectedOutput: "GEO opportunities" },
      { agentSlug: "ANALYTICS_AGENT", objective: "Tie SEO opportunities to click, traffic, and conversion context.", expectedOutput: "SEO analytics context" },
    ],
  },
  CONTENT_MARKETING_SPRINT: {
    id: "CONTENT_MARKETING_SPRINT",
    title: "Content Marketing Sprint",
    companyId: "web-growth",
    objective: "Build a content-marketing sprint that coordinates clusters, calendars, gap analysis, internal linking, FAQs, snippets, and repurposing plans.",
    approvalClass: "A1",
    workflows: ["CONTENT_PUBLISHING_WORKFLOW", "SEO_GROWTH_WORKFLOW"],
    successCriteria: [
      "Content clusters and editorial priorities are documented",
      "FAQ, snippet, AEO, and GEO opportunities are attached to the content plan",
      "Publishing cadence and refresh planning are recorded for future execution",
    ],
    specialistBlueprints: [
      { agentSlug: "CONTENT_STRATEGIST_AGENT", objective: "Define topical maps, editorial calendar, and refresh schedule.", expectedOutput: "Editorial growth plan" },
      { agentSlug: "EDITORIAL_MANAGER_AGENT", objective: "Set publishing cadence, review checkpoints, and quality thresholds.", expectedOutput: "Editorial operations plan" },
      { agentSlug: "SEO_AGENT", objective: "Map topic gaps, competitor gaps, and snippet opportunities to the content plan.", expectedOutput: "Content SEO opportunity map" },
      { agentSlug: "INTERNAL_LINKING_AGENT", objective: "Define internal-linking paths across target pages and clusters.", expectedOutput: "Internal-linking expansion plan" },
      { agentSlug: "COPYWRITER_AGENT", objective: "Define draft content packages and CTA structure requirements.", expectedOutput: "Content package brief" },
      { agentSlug: "SOCIAL_MEDIA_AGENT", objective: "Plan cross-channel repurposing for academy and content assets.", expectedOutput: "Social repurposing plan" },
    ],
  },
  REVENUE_OPPORTUNITY_REVIEW: {
    id: "REVENUE_OPPORTUNITY_REVIEW",
    title: "Revenue Opportunity Review",
    companyId: "web-growth",
    objective: "Coordinate analytics, CRO, revenue operations, affiliate, digital product, newsletter, and AdSense opportunities into a revenue-growth operating plan.",
    approvalClass: "A1",
    workflows: ["ANALYTICS_REVIEW_WORKFLOW", "WEEKLY_AGENCY_OPERATIONS_WORKFLOW", "ADSENSE_READINESS_WORKFLOW"],
    successCriteria: [
      "Revenue opportunities are prioritized across services, content, products, and conversion paths",
      "Affiliate, AdSense, newsletter, and digital-product opportunities are documented without live external actions",
      "Executive revenue reporting is generated with next recommended priorities",
    ],
    specialistBlueprints: [
      { agentSlug: "ANALYTICS_AGENT", objective: "Summarize revenue-facing KPIs, traffic, leads, and conversion signals.", expectedOutput: "Revenue analytics summary" },
      { agentSlug: "CRO_AGENT", objective: "Translate performance signals into conversion and funnel opportunities.", expectedOutput: "CRO growth backlog" },
      { agentSlug: "REVENUE_OPERATIONS_AGENT", objective: "Prioritize highest-fit revenue opportunities across services and recurring offers.", expectedOutput: "Revenue priority ladder" },
      { agentSlug: "ADSENSE_AGENT", objective: "Review AdSense readiness, policy risk, and content quality gaps.", expectedOutput: "AdSense readiness report" },
      { agentSlug: "AFFILIATE_MANAGER_AGENT", objective: "Map affiliate opportunities, placement strategy, and compliance considerations.", expectedOutput: "Affiliate opportunity map" },
      { agentSlug: "DIGITAL_PRODUCT_AGENT", objective: "Identify templates, guides, toolkits, and other digital-product opportunities.", expectedOutput: "Digital product opportunities" },
      { agentSlug: "NEWSLETTER_AGENT", objective: "Define newsletter growth, lead-magnet, and promotion opportunities.", expectedOutput: "Newsletter growth plan" },
      { agentSlug: "MARKETING_STRATEGIST_AGENT", objective: "Translate revenue findings into campaign and pipeline priorities.", expectedOutput: "Growth campaign priorities" },
    ],
  },
  LEAD_RESEARCH: {
    id: "LEAD_RESEARCH",
    title: "Lead Research Mission",
    companyId: "web-growth",
    objective: "Create a compliant lead-research mission with research, audits, intelligence, CRM, drafts, QA, documentation, and memory capture.",
    approvalClass: "A1",
    workflows: ["LEAD_RESEARCH_WORKFLOW", "HUMAN_APPROVED_OUTREACH_WORKFLOW"],
    successCriteria: [
      "Lead workflow is routed correctly",
      "Approval boundaries are preserved",
      "Persistent state records the full mission chain",
    ],
    specialistBlueprints: [
      { agentSlug: "MARKETING_STRATEGIST_AGENT", objective: "Confirm target segment and quota framing.", expectedOutput: "Lead mission brief" },
      { agentSlug: "LEAD_RESEARCH_AGENT", objective: "Define qualified lead collection plan without sending outreach.", expectedOutput: "Lead research plan" },
      { agentSlug: "WEBSITE_AUDIT_AGENT", objective: "Define mini-audit structure for accepted leads.", expectedOutput: "Audit framework" },
      { agentSlug: "BUSINESS_INTELLIGENCE_AGENT", objective: "Define enrichment and personalization fields.", expectedOutput: "Intelligence enrichment plan" },
      { agentSlug: "CRM_AGENT", objective: "Define status tracking and follow-up state management.", expectedOutput: "CRM state plan" },
      { agentSlug: "OUTREACH_DRAFTING_AGENT", objective: "Define draft structure without sending or creating external actions.", expectedOutput: "Outreach draft spec" },
    ],
  },
  NEWSLETTER_CAMPAIGN: {
    id: "NEWSLETTER_CAMPAIGN",
    title: "Newsletter Campaign",
    companyId: "web-growth",
    objective: "Coordinate content, marketing, CRM, client-safe review, and documentation for a newsletter campaign.",
    approvalClass: "A1",
    workflows: ["HUMAN_APPROVED_OUTREACH_WORKFLOW"],
    successCriteria: ["Newsletter content is drafted and logged", "Approval queue is respected"],
    specialistBlueprints: [
      { agentSlug: "CONTENT_STRATEGIST_AGENT", objective: "Define the newsletter theme and supporting content.", expectedOutput: "Newsletter brief" },
      { agentSlug: "NEWSLETTER_AGENT", objective: "Prepare the newsletter draft and list-growth angle.", expectedOutput: "Newsletter draft" },
      { agentSlug: "CRM_AGENT", objective: "Prepare the associated list and status context.", expectedOutput: "CRM newsletter state" },
    ],
  },
};

export function getMissionTemplate(templateId) {
  const template = missionTemplates[templateId];
  if (!template) {
    throw new Error(`Unknown mission template: ${templateId}`);
  }
  return template;
}
