import path from "node:path";

export const WGOS_ROOT = path.resolve(process.cwd(), "WGOS");

export const priorities = [
  "Compliance",
  "UX",
  "Content Quality",
  "SEO",
  "Performance",
  "Conversions",
  "Revenue",
];

export const statuses = [
  "BACKLOG",
  "READY",
  "IN_PROGRESS",
  "BLOCKED",
  "WAITING_APPROVAL",
  "FAILED_QA",
  "COMPLETED",
  "ARCHIVED",
];

export const approvalClasses = [
  {
    id: "A0",
    name: "Internal documentation only",
    usage: "No external system access and no state changes.",
  },
  {
    id: "A1",
    name: "Local analysis and drafts",
    usage: "Local repo work, planning, reporting, and non-live asset creation.",
  },
  {
    id: "A2",
    name: "Read-only external observation",
    usage: "Human-approved live observation after login or attachment.",
  },
  {
    id: "A3",
    name: "State-changing external action",
    usage: "Any live change outside the repo with explicit approval.",
  },
  {
    id: "A4",
    name: "Critical irreversible action",
    usage: "Production, financial, DNS, billing, or irreversible changes.",
  },
];

export const departments = [
  {
    id: "executive",
    name: "Executive",
    summary: "Mission intake, routing, approvals, governance, and executive reporting.",
  },
  {
    id: "design",
    name: "Design",
    summary: "Product strategy, UX, brand systems, and motion direction.",
  },
  {
    id: "engineering",
    name: "Engineering",
    summary: "Implementation, performance, accessibility, QA support, and deployment prep.",
  },
  {
    id: "search",
    name: "Search",
    summary: "SEO, technical SEO, AEO, GEO, schema, and Search Console analysis.",
  },
  {
    id: "publishing",
    name: "Publishing",
    summary: "Editorial planning, writing strategy, publishing, proofreading, and internal linking.",
  },
  {
    id: "marketing",
    name: "Marketing",
    summary: "Lead research, audits, outreach drafts, CRM hygiene, and demand generation.",
  },
  {
    id: "revenue",
    name: "Revenue",
    summary: "CRO, monetization strategy, affiliate planning, product opportunities, and analytics.",
  },
  {
    id: "client",
    name: "Client",
    summary: "Sales consultation, proposals, onboarding, and client success transitions.",
  },
  {
    id: "operations",
    name: "Operations",
    summary: "Operating cadence, process reliability, task hygiene, and service delivery control.",
  },
  {
    id: "qa",
    name: "QA",
    summary: "Independent validation of quality, readiness, and standards compliance.",
  },
  {
    id: "documentation",
    name: "Documentation",
    summary: "Traceability, memory integrity, and durable handoff records.",
  },
];

export const agents = [
  {
    id: "ceo_operator",
    slug: "CEO_OPERATOR_AGENT",
    department: "executive",
    title: "CEO Operator",
    mission: "Translate a business objective into a mission with priority, success metrics, and resource boundaries.",
    capabilities: [
      "Define mission intent",
      "Approve department mix",
      "Escalate strategic tradeoffs",
      "Review executive outcomes",
    ],
    skills: ["BUSINESS_MODEL", "OPERATIONS"],
    outputs: ["Mission brief", "Executive summary", "Priority decision"],
  },
  {
    id: "workflow_orchestrator",
    slug: "WORKFLOW_ORCHESTRATOR_AGENT",
    department: "executive",
    title: "Workflow Orchestrator",
    mission: "Route missions through the correct workflows, departments, approvals, and validation sequence.",
    capabilities: [
      "Select workflows",
      "Sequence dependencies",
      "Route specialist tasks",
      "Escalate approval pauses",
    ],
    skills: ["OPERATIONS", "TESTING"],
    outputs: ["Task routing plan", "Dependency map", "Approval map"],
  },
  {
    id: "project_manager",
    slug: "PROJECT_MANAGER_AGENT",
    department: "executive",
    title: "Project Manager",
    mission: "Own task IDs, status control, dependencies, blockers, and handoff readiness.",
    capabilities: [
      "Create task boards",
      "Manage statuses",
      "Track risks",
      "Prepare handoffs",
    ],
    skills: ["OPERATIONS"],
    outputs: ["Task board", "Status updates", "Risk register"],
  },
  {
    id: "knowledge_manager",
    slug: "KNOWLEDGE_MANAGER_AGENT",
    department: "executive",
    title: "Knowledge Manager",
    mission: "Convert execution into reusable memory, patterns, and lessons.",
    capabilities: [
      "Update memory",
      "Record decisions",
      "Capture lessons",
      "Maintain next actions",
    ],
    skills: ["OPERATIONS"],
    outputs: ["Memory updates", "Decision log", "Learning record"],
  },
  {
    id: "documentation_manager",
    slug: "DOCUMENTATION_AGENT",
    department: "executive",
    title: "Documentation Manager",
    mission: "Ensure every meaningful task ends with durable, readable records.",
    capabilities: [
      "Write reports",
      "Maintain changelog",
      "Audit completeness",
      "Normalize artifacts",
    ],
    skills: ["OPERATIONS"],
    outputs: ["Mission report", "Documentation checklist", "Closeout summary"],
  },
  {
    id: "product_strategist",
    slug: "PRODUCT_STRATEGIST_AGENT",
    department: "design",
    title: "Product Strategist",
    mission: "Shape digital products and service experiences around user needs and revenue intent.",
    capabilities: ["Define positioning", "Map journeys", "Clarify offer strategy"],
    skills: ["CRO", "COPYWRITING"],
    outputs: ["Product strategy brief", "User journey map"],
  },
  {
    id: "ui_ux_designer",
    slug: "UI_UX_DESIGN_AGENT",
    department: "design",
    title: "UI UX Designer",
    mission: "Create structured, premium interfaces that support clarity, trust, and conversion.",
    capabilities: ["Wireframe flows", "Design layouts", "Assess UX friction"],
    skills: ["ACCESSIBILITY", "CRO"],
    outputs: ["Wireframes", "Interface notes", "UX audit"],
  },
  {
    id: "brand_designer",
    slug: "BRAND_DESIGN_AGENT",
    department: "design",
    title: "Brand Designer",
    mission: "Build consistent visual systems that align brand, trust, and premium positioning.",
    capabilities: ["Define brand system", "Review consistency", "Design brand assets"],
    skills: ["COPYWRITING"],
    outputs: ["Brand guidance", "Asset direction"],
  },
  {
    id: "motion_graphics",
    slug: "MOTION_GRAPHICS_AGENT",
    department: "design",
    title: "Motion Graphics Designer",
    mission: "Plan motion that supports comprehension without hurting performance or accessibility.",
    capabilities: ["Motion planning", "Reduced-motion review", "Animation specification"],
    skills: ["GSAP", "FRAMER_MOTION", "PERFORMANCE"],
    outputs: ["Motion plan", "Animation guidance"],
  },
  {
    id: "frontend_engineer",
    slug: "FRONTEND_ENGINEER_AGENT",
    department: "engineering",
    title: "Frontend Engineer",
    mission: "Implement premium, accessible user interfaces in the approved frontend stack.",
    capabilities: ["Build interfaces", "Refactor components", "Protect SEO surfaces"],
    skills: ["NEXTJS", "TAILWIND", "TYPESCRIPT", "ACCESSIBILITY"],
    outputs: ["Frontend implementation", "Validation notes"],
  },
  {
    id: "backend_engineer",
    slug: "BACKEND_ENGINEER_AGENT",
    department: "engineering",
    title: "Backend Engineer",
    mission: "Design and implement stable, secure backend logic and service integrations.",
    capabilities: ["Implement server logic", "Design APIs", "Guard data flows"],
    skills: ["TYPESCRIPT", "TESTING"],
    outputs: ["Backend implementation", "Service notes"],
  },
  {
    id: "full_stack_engineer",
    slug: "FULL_STACK_ENGINEER_AGENT",
    department: "engineering",
    title: "Full Stack Engineer",
    mission: "Bridge application architecture across frontend, backend, and data flow concerns.",
    capabilities: ["Cross-stack implementation", "Route integration", "System fixes"],
    skills: ["NEXTJS", "TYPESCRIPT", "TESTING"],
    outputs: ["Integrated feature", "Cross-layer validation"],
  },
  {
    id: "performance_engineer",
    slug: "PERFORMANCE_ENGINEER_AGENT",
    department: "engineering",
    title: "Performance Engineer",
    mission: "Protect Core Web Vitals and remove systemic performance drag.",
    capabilities: ["Profile issues", "Recommend fixes", "Validate performance changes"],
    skills: ["PERFORMANCE", "NEXTJS"],
    outputs: ["Performance audit", "Optimization plan"],
  },
  {
    id: "accessibility_engineer",
    slug: "ACCESSIBILITY_ENGINEER_AGENT",
    department: "engineering",
    title: "Accessibility Engineer",
    mission: "Keep experiences perceivable, operable, understandable, and robust.",
    capabilities: ["Audit semantics", "Review keyboard flows", "Assess contrast and motion"],
    skills: ["ACCESSIBILITY", "TESTING"],
    outputs: ["Accessibility audit", "Fix list"],
  },
  {
    id: "qa_engineer",
    slug: "QA_ENGINEER_AGENT",
    department: "engineering",
    title: "QA Engineer",
    mission: "Validate outputs against requirements, regressions, and release criteria.",
    capabilities: ["Run checks", "Write QA notes", "Reject incomplete work"],
    skills: ["TESTING"],
    outputs: ["QA report", "Pass/fail decision"],
  },
  {
    id: "deployment_engineer",
    slug: "DEPLOYMENT_ENGINEER_AGENT",
    department: "engineering",
    title: "Deployment Engineer",
    mission: "Prepare safe deployment plans and release procedures without bypassing approvals.",
    capabilities: ["Plan release", "Check environments", "Assess rollback paths"],
    skills: ["DEPLOYMENT", "TESTING"],
    outputs: ["Deployment plan", "Release checklist"],
  },
  {
    id: "seo",
    slug: "SEO_AGENT",
    department: "search",
    title: "SEO",
    mission: "Improve organic visibility through intent-led content and search strategy.",
    capabilities: ["Map keywords", "Define clusters", "Shape snippets"],
    skills: ["SEO", "AEO", "GEO", "COPYWRITING"],
    outputs: ["SEO strategy", "Optimization plan"],
  },
  {
    id: "technical_seo",
    slug: "TECHNICAL_SEO_AGENT",
    department: "search",
    title: "Technical SEO",
    mission: "Protect indexability, crawlability, metadata, canonicals, and route-safe search infrastructure.",
    capabilities: ["Audit technical SEO", "Review canonicals", "Guard route governance"],
    skills: ["SEO", "CODEX_SEO", "SCHEMA", "TESTING"],
    outputs: ["Technical SEO audit", "Fix backlog"],
  },
  {
    id: "aeo",
    slug: "AEO_AGENT",
    department: "search",
    title: "AEO",
    mission: "Structure content for answer engines, rich extraction, and question-led discovery.",
    capabilities: ["Shape direct answers", "Identify FAQ opportunities", "Reduce ambiguity"],
    skills: ["AEO", "SCHEMA", "COPYWRITING"],
    outputs: ["AEO brief", "Question-answer map"],
  },
  {
    id: "geo",
    slug: "GEO_AGENT",
    department: "search",
    title: "GEO",
    mission: "Improve generative-engine discoverability through structured, verifiable content signals.",
    capabilities: ["Assess generative citations", "Improve trust signals", "Increase extractability"],
    skills: ["GEO", "SCHEMA", "SEO"],
    outputs: ["GEO audit", "Signal improvement plan"],
  },
  {
    id: "schema",
    slug: "SCHEMA_AGENT",
    department: "search",
    title: "Schema",
    mission: "Design and validate schema markup that matches visible content and search intent.",
    capabilities: ["Plan schema", "Audit markup", "Validate eligibility"],
    skills: ["SCHEMA", "SEO"],
    outputs: ["Schema plan", "Schema validation report"],
  },
  {
    id: "search_console",
    slug: "SEARCH_CONSOLE_AGENT",
    department: "search",
    title: "Search Console",
    mission: "Interpret Search Console signals without bypassing human approval for protected actions.",
    capabilities: ["Review performance", "Assess indexing", "Identify opportunities"],
    skills: ["SEARCH_CONSOLE", "SEO", "GA4"],
    outputs: ["Search Console report", "Opportunity list"],
  },
  {
    id: "editorial_manager",
    slug: "EDITORIAL_MANAGER_AGENT",
    department: "publishing",
    title: "Editorial Manager",
    mission: "Plan practical, people-first content programs with clear search intent.",
    capabilities: ["Own editorial calendars", "Prioritize content", "Review quality bar"],
    skills: ["CONTENT_WRITING", "SEO"],
    outputs: ["Editorial plan", "Publishing priorities"],
  },
  {
    id: "content_strategist",
    slug: "CONTENT_STRATEGIST_AGENT",
    department: "publishing",
    title: "Content Strategist",
    mission: "Turn search, audience, and conversion goals into briefs and content systems.",
    capabilities: ["Create briefs", "Map clusters", "Plan refreshes"],
    skills: ["CONTENT_WRITING", "SEO", "AEO"],
    outputs: ["Content brief", "Cluster plan"],
  },
  {
    id: "copywriter",
    slug: "COPYWRITER_AGENT",
    department: "publishing",
    title: "Copywriter",
    mission: "Write clear, persuasive, trustworthy copy aligned to search intent and conversions.",
    capabilities: ["Write pages", "Draft emails", "Improve messaging"],
    skills: ["COPYWRITING", "CONTENT_WRITING", "CRO"],
    outputs: ["Copy draft", "Messaging recommendations"],
  },
  {
    id: "proofreader",
    slug: "PROOFREADER_AGENT",
    department: "publishing",
    title: "Proofreader",
    mission: "Improve clarity, grammar, consistency, and credibility without flattening meaning.",
    capabilities: ["Proofread drafts", "Check consistency", "Flag weak claims"],
    skills: ["CONTENT_WRITING"],
    outputs: ["Proofread draft", "Issue list"],
  },
  {
    id: "internal_linking",
    slug: "INTERNAL_LINKING_AGENT",
    department: "publishing",
    title: "Internal Linking",
    mission: "Strengthen content relationships, discovery, and conversion paths through deliberate internal links.",
    capabilities: ["Audit links", "Create link plans", "Map supporting content"],
    skills: ["SEO", "CONTENT_WRITING"],
    outputs: ["Internal linking plan", "Link insertion brief"],
  },
  {
    id: "marketing_strategist",
    slug: "MARKETING_STRATEGIST_AGENT",
    department: "marketing",
    title: "Marketing Strategist",
    mission: "Prioritize growth channels, campaigns, and messaging around revenue impact.",
    capabilities: ["Define campaigns", "Prioritize channels", "Align growth and offer strategy"],
    skills: ["CRO", "COPYWRITING"],
    outputs: ["Marketing plan", "Channel strategy"],
  },
  {
    id: "lead_research",
    slug: "LEAD_RESEARCH_AGENT",
    department: "marketing",
    title: "Lead Research",
    mission: "Find qualified businesses and document outreach-ready opportunities.",
    capabilities: ["Research prospects", "Score opportunities", "Compile lead lists"],
    skills: ["LEAD_RESEARCH", "CONTROLLED_BROWSER", "OUTREACH"],
    outputs: ["Lead research report", "Qualified leads CSV"],
  },
  {
    id: "website_audit",
    slug: "WEBSITE_AUDIT_AGENT",
    department: "marketing",
    title: "Website Audit",
    mission: "Turn visible website weaknesses into serviceable business opportunities.",
    capabilities: ["Audit websites", "Estimate opportunity", "Recommend service paths"],
    skills: ["SEO", "PERFORMANCE", "ACCESSIBILITY", "CRO"],
    outputs: ["Website audit", "Opportunity summary"],
  },
  {
    id: "business_intelligence",
    slug: "BUSINESS_INTELLIGENCE_AGENT",
    department: "marketing",
    title: "Business Intelligence",
    mission: "Track operational, commercial, and market signals that guide better priorities.",
    capabilities: ["Track KPIs", "Assess patterns", "Summarize business trends"],
    skills: ["GA4", "LEAD_RESEARCH"],
    outputs: ["KPI snapshot", "Trend report"],
  },
  {
    id: "outreach_drafting",
    slug: "OUTREACH_DRAFTING_AGENT",
    department: "marketing",
    title: "Outreach Drafting",
    mission: "Create personalized outreach drafts that stay human-approved and evidence-based.",
    capabilities: ["Draft emails", "Personalize messaging", "Prepare follow-up copy"],
    skills: ["OUTREACH", "COPYWRITING", "GMAIL"],
    outputs: ["Outreach draft", "Follow-up sequence"],
  },
  {
    id: "crm",
    slug: "CRM_AGENT",
    department: "marketing",
    title: "CRM",
    mission: "Maintain clean lead and client pipeline records with status discipline.",
    capabilities: ["Update pipeline", "Track follow-ups", "Log approvals"],
    skills: ["OUTREACH", "LEAD_RESEARCH"],
    outputs: ["CRM update", "Pipeline summary"],
  },
  {
    id: "follow_up",
    slug: "FOLLOW_UP_AGENT",
    department: "marketing",
    title: "Follow Up",
    mission: "Maintain safe, timely follow-up sequences after human-approved outreach actions.",
    capabilities: ["Plan cadence", "Draft reminders", "Track reply states"],
    skills: ["OUTREACH", "GMAIL"],
    outputs: ["Follow-up plan", "Reminder drafts"],
  },
  {
    id: "social_media",
    slug: "SOCIAL_MEDIA_AGENT",
    department: "marketing",
    title: "Social Media",
    mission: "Turn business and content goals into social distribution plans and assets.",
    capabilities: ["Repurpose content", "Plan channels", "Draft social posts"],
    skills: ["COPYWRITING", "CONTENT_WRITING"],
    outputs: ["Social plan", "Post drafts"],
  },
  {
    id: "newsletter",
    slug: "NEWSLETTER_AGENT",
    department: "marketing",
    title: "Newsletter",
    mission: "Convert knowledge and offers into useful email content and list-growth assets.",
    capabilities: ["Plan newsletters", "Draft issues", "Map list growth ideas"],
    skills: ["COPYWRITING", "CONTENT_WRITING", "GMAIL"],
    outputs: ["Newsletter brief", "Draft issue"],
  },
  {
    id: "cro",
    slug: "CRO_AGENT",
    department: "revenue",
    title: "CRO",
    mission: "Improve conversion paths, message clarity, and funnel efficiency.",
    capabilities: ["Audit conversion paths", "Recommend tests", "Prioritize friction fixes"],
    skills: ["CRO", "COPYWRITING", "GA4"],
    outputs: ["CRO audit", "Experiment backlog"],
  },
  {
    id: "adsense",
    slug: "ADSENSE_AGENT",
    department: "revenue",
    title: "AdSense",
    mission: "Evaluate monetization readiness without compromising content quality or policy safety.",
    capabilities: ["Audit policy readiness", "Flag thin content", "Recommend trust improvements"],
    skills: ["ADSENSE", "SEO", "CONTENT_WRITING"],
    outputs: ["AdSense readiness report", "Compliance backlog"],
  },
  {
    id: "affiliate_manager",
    slug: "AFFILIATE_MANAGER_AGENT",
    department: "revenue",
    title: "Affiliate Manager",
    mission: "Design trust-safe affiliate opportunities that match audience needs and business positioning.",
    capabilities: ["Research offers", "Assess fit", "Plan comparisons"],
    skills: ["COPYWRITING", "SEO"],
    outputs: ["Affiliate opportunity map", "Offer shortlist"],
  },
  {
    id: "digital_product",
    slug: "DIGITAL_PRODUCT_AGENT",
    department: "revenue",
    title: "Digital Product",
    mission: "Identify and shape high-leverage digital products and templates.",
    capabilities: ["Scope products", "Define assets", "Assess repeatability"],
    skills: ["COPYWRITING", "CRO"],
    outputs: ["Product concept", "Delivery outline"],
  },
  {
    id: "saas_planner",
    slug: "SAAS_PLANNER_AGENT",
    department: "revenue",
    title: "SaaS Planner",
    mission: "Translate problems into viable SaaS opportunities, scope, and validation plans.",
    capabilities: ["Assess SaaS ideas", "Define MVPs", "Map revenue fit"],
    skills: ["CRO", "COPYWRITING"],
    outputs: ["SaaS concept brief", "MVP scope"],
  },
  {
    id: "analytics",
    slug: "ANALYTICS_AGENT",
    department: "revenue",
    title: "Analytics",
    mission: "Turn data into decisions for content, conversion, and revenue priorities.",
    capabilities: ["Analyze KPIs", "Summarize performance", "Recommend actions"],
    skills: ["GA4", "SEO", "CRO"],
    outputs: ["Analytics report", "Decision support summary"],
  },
  {
    id: "revenue_operations",
    slug: "REVENUE_OPERATIONS_AGENT",
    department: "revenue",
    title: "Revenue Operations",
    mission: "Prioritize the fastest, safest, highest-fit revenue opportunities across services, content, products, and conversion paths.",
    capabilities: ["Prioritize income opportunities", "Compare delivery difficulty", "Map repeatable offers", "Recommend revenue focus"],
    skills: ["CRO", "COPYWRITING", "GA4", "BUSINESS_MODEL"],
    outputs: ["Revenue opportunity report", "Priority ladder", "Offer recommendation"],
  },
  {
    id: "sales_consultant",
    slug: "SALES_CONSULTANT_AGENT",
    department: "client",
    title: "Sales Consultant",
    mission: "Clarify client needs, scope alignment, and the path to proposal fit.",
    capabilities: ["Run discovery", "Clarify needs", "Summarize offer fit"],
    skills: ["COPYWRITING", "CRO"],
    outputs: ["Discovery summary", "Fit assessment"],
  },
  {
    id: "proposal_writer",
    slug: "PROPOSAL_WRITER_AGENT",
    department: "client",
    title: "Proposal Writer",
    mission: "Turn scoped opportunities into persuasive, credible proposals.",
    capabilities: ["Write proposals", "Frame outcomes", "Clarify scope and price"],
    skills: ["COPYWRITING"],
    outputs: ["Proposal draft", "Scope summary"],
  },
  {
    id: "client_success",
    slug: "CLIENT_SUCCESS_AGENT",
    department: "client",
    title: "Client Success",
    mission: "Keep delivery aligned with client expectations, milestones, and risk communication.",
    capabilities: ["Track milestones", "Summarize status", "Flag expectation risks"],
    skills: ["COPYWRITING"],
    outputs: ["Client status note", "Risk summary"],
  },
  {
    id: "client_onboarding",
    slug: "CLIENT_ONBOARDING_AGENT",
    department: "client",
    title: "Client Onboarding",
    mission: "Set up new projects with clean inputs, approvals, and delivery foundations.",
    capabilities: ["Collect inputs", "Structure kickoff", "Confirm dependencies"],
    skills: ["COPYWRITING"],
    outputs: ["Onboarding checklist", "Kickoff package"],
  },
];

export const skills = [
  "NEXTJS",
  "TAILWIND",
  "TYPESCRIPT",
  "GSAP",
  "FRAMER_MOTION",
  "SEO",
  "CODEX_SEO",
  "AEO",
  "GEO",
  "ADSENSE",
  "CONTENT_WRITING",
  "COPYWRITING",
  "SCHEMA",
  "GA4",
  "SEARCH_CONSOLE",
  "GMAIL",
  "CONTROLLED_BROWSER",
  "ACCESSIBILITY",
  "PERFORMANCE",
  "TESTING",
  "DEPLOYMENT",
  "CRO",
  "LEAD_RESEARCH",
  "OUTREACH",
  "BUSINESS_MODEL",
  "OPERATIONS",
];

export const workflows = [
  {
    slug: "WORKFLOW_ORCHESTRATION",
    title: "Workflow Orchestration",
    trigger: "Any new mission that needs routing and dependency planning.",
    departments: ["executive", "operations", "documentation"],
  },
  {
    slug: "WEBSITE_REBUILD_WORKFLOW",
    title: "Website Rebuild Workflow",
    trigger: "A website needs redesign, re-platforming, or major structural improvement.",
    departments: ["executive", "design", "engineering", "search", "publishing", "qa", "documentation"],
  },
  {
    slug: "SEO_GROWTH_WORKFLOW",
    title: "SEO Growth Workflow",
    trigger: "A site needs rankings, snippets, internal links, trust, or technical SEO improvements.",
    departments: ["search", "publishing", "revenue", "qa", "documentation"],
  },
  {
    slug: "CONTENT_PUBLISHING_WORKFLOW",
    title: "Content Publishing Workflow",
    trigger: "A content program or article batch needs planning, drafting, review, and publishing readiness.",
    departments: ["publishing", "search", "qa", "documentation"],
  },
  {
    slug: "ADSENSE_READINESS_WORKFLOW",
    title: "AdSense Readiness Workflow",
    trigger: "A property needs policy-safe monetization readiness evaluation.",
    departments: ["revenue", "publishing", "search", "qa", "documentation"],
  },
  {
    slug: "LEAD_RESEARCH_WORKFLOW",
    title: "Lead Research Workflow",
    trigger: "The marketing team needs qualified leads and audit-ready outreach opportunities.",
    departments: ["marketing", "revenue", "documentation"],
  },
  {
    slug: "HUMAN_APPROVED_OUTREACH_WORKFLOW",
    title: "Human Approved Outreach Workflow",
    trigger: "A campaign needs draft outreach and approval-gated follow-up plans.",
    departments: ["marketing", "client", "documentation"],
  },
  {
    slug: "CLIENT_PROJECT_DELIVERY_WORKFLOW",
    title: "Client Project Delivery Workflow",
    trigger: "A client engagement needs end-to-end discovery through delivery preparation.",
    departments: ["client", "design", "engineering", "search", "qa", "documentation"],
  },
  {
    slug: "ANALYTICS_REVIEW_WORKFLOW",
    title: "Analytics Review Workflow",
    trigger: "A business needs KPI review, reporting, and next-step recommendations.",
    departments: ["revenue", "marketing", "executive", "documentation"],
  },
  {
    slug: "WEEKLY_AGENCY_OPERATIONS_WORKFLOW",
    title: "Weekly Agency Operations Workflow",
    trigger: "The company needs a recurring operating review across delivery, growth, and risk.",
    departments: ["executive", "operations", "marketing", "revenue", "documentation"],
  },
  {
    slug: "CONTROLLED_BROWSER_WORKFLOW",
    title: "Controlled Browser Workflow",
    trigger: "A task needs browser observation with login, 2FA, or human-gated external steps.",
    departments: ["executive", "search", "marketing", "documentation"],
  },
  {
    slug: "DOCUMENTATION_UPDATE_WORKFLOW",
    title: "Documentation Update Workflow",
    trigger: "A mission or task changed system state and requires durable records.",
    departments: ["documentation", "executive"],
  },
  {
    slug: "QA_AND_RELEASE_WORKFLOW",
    title: "QA And Release Workflow",
    trigger: "A build or deliverable needs validation and release readiness review.",
    departments: ["qa", "engineering", "documentation"],
  },
];

export const integrations = [
  "browser",
  "github",
  "gmail",
  "crm",
  "search-console",
  "ga4",
  "pagespeed",
  "lighthouse",
  "cloudflare",
  "namecheap",
  "vercel",
  "figma",
  "maps",
  "search",
  "business-directories",
  "filesystem",
  "docs",
  "csv",
  "images",
];

export const templates = [
  "TASK_BOARD_TEMPLATE",
  "AGENT_REPORT_TEMPLATE",
  "LEAD_RESEARCH_REPORT_TEMPLATE",
  "WEBSITE_AUDIT_REPORT_TEMPLATE",
  "OUTREACH_DRAFT_TEMPLATE",
  "SEO_TASK_REPORT_TEMPLATE",
  "CONTENT_BRIEF_TEMPLATE",
  "QA_REPORT_TEMPLATE",
  "DEPLOYMENT_REPORT_TEMPLATE",
  "WEEKLY_REPORT_TEMPLATE",
  "DECISION_LOG_TEMPLATE",
  "MEMORY_UPDATE_TEMPLATE",
];

export const tenants = [
  {
    id: "WG-001",
    slug: "web-growth",
    name: "Web Growth",
    industry: "Digital Growth Platform",
    country: "Nigeria",
    timezone: "Africa/Lagos",
    owner: "Vicky",
    services: [
      "Website Design",
      "SEO",
      "Technical SEO",
      "Performance Optimization",
      "CRO",
      "Content Publishing",
    ],
    status: "ACTIVE",
    currentPhase: "Phase 9-ready platform tenant",
  },
  {
    id: "CL-000",
    slug: "client-template",
    name: "Client Template",
    industry: "Template",
    country: "TBD",
    timezone: "TBD",
    owner: "WGOS",
    services: ["Template"],
    status: "TEMPLATE",
    currentPhase: "Reusable onboarding seed",
  },
];

export const demoMission = {
  id: "M-2026-07-08-WGOS-FULL-WIRING",
  taskPrefix: "T-2026-07-08-WGOS",
  companyId: "WG-001",
  objective: "Prove WGOS can orchestrate a multi-department internal mission from intake through reporting, learning, and platform updates.",
  successCriteria: [
    "Mission brief created",
    "Task board created",
    "Agent routing documented",
    "Report generated",
    "Memory updated",
    "Learning record stored",
    "KPI snapshot produced",
    "Cross-company-safe summary produced",
  ],
};
